config:
    nick: "MutinyIRC"
    server: "irc.esper.net"
    port: 6667
  # uncomment this if there is a pass required.
  # pass: "secretpasswordhere"
    message_interval: 750
    command_prefix: "."
    channels:
        - "#mutinyirc"
    verbose: true
  # startup_commands:
  #     - "PRIVMSG NickServ :identify MutinyIRC secretpassword"

irc_to_game:
    prefix:
        message: "§d[IRC]§7 "
        action: "§d[IRC] §7* "
        nick: "§d[IRC] §7* "
    suffix:
        message: "§r: "
        action: ""
        nick: ""
    send_colors: true
    relay_actions: true

game_to_irc:
    prefix:
        message: "<"
        action: "* "
    suffix:
        message: "> "
        action: ""

    send_colors: true
    relay_actions: true


# ## IGNORE EVERYTHING BELOW IF YOU ## #
# ## DO NOT KNOW WHAT YOU ARE DOING ## #

advanced:
    listeners:
        - "DefaultChatHandler"