config:
    nick: "MutinyIRC"
    server: "irc.esper.net"
    port: 6667
  # pass: "secretpasswordhere"
    message_interval: 750
    command_prefix: "."
    channels:
        - "#mutinyirc"
    verbose: true
  # startup_commands:
  #     - "PRIVMSG NickServ :identify MutinyIRC secretpassword"

irc_to_game:
    prefix: "&d[IRC]&7 "
    messages:
        join: "%user% has joined %channel%"
        part: "%user% has left %channel%"
        kick: "%user% was kicked by %kicker%"
        msg: "%user%: %msg%"
        nick: "%oldnick% is now known as %newnick%"
        me: "* %user% %action%"
    relay:
        join: true
        part: true
        kick: false
        msg: true
        nick: true
        me: true
        color: true

game_to_irc:
    prefix: ""
    name_format: "%dname%" 
    messages:
        join: "%nf%&r has joined."
        part: "%nf%&r has left."
        kick: "%nf%&r was kicked (%reason%)."
        msg: "<%nf%&r> %msg%"
        me: "* %nf%&r %action%"
    relay:
        join: true
        part: true
        kick: true
        msg: true
        me: true
        color: true

advanced:
    handlers:
        - "DefaultChatHandler"