# See http://dev.bukkit.org/bukkit-plugins/mutinyirc/pages/configuration/
# for help on setting up MutinyIRC configuration.
config:
    nick: "MutinyIRC"
    server: "irc.esper.net"
    port: 6667
  # pass: "secretpasswordhere"
    message_interval: 750
    command_prefix: "."
    channels:
        - "#somechannelhere"
    verbose: true
  # startup_commands:
  #     - "PRIVMSG NickServ :identify MutinyIRC secretpassword"

irc_to_game:
    prefix: "&d[IRC]&7 "
    messages:
        join: "%user% has joined %channel%"
        part: "%user% has left %channel%"
        kick: "%user% was kicked by %kicker%"
        msg: "%user%&f: %msg%"
        nick: "%oldnick% is now known as %newnick%"
        me: "* %user% %action%"
    relay:
        join: true
        part: true
        kick: false
        msg: true
        nick: true
        me: true
        color: true

game_to_irc:
    prefix: ""
    name_format: "%dname%" 
    messages:
        join: "%dname%&r has joined."
        part: "%dname%&r has left."
        kick: "%dname%&r was kicked (%reason%)."
        msg: "<%nf%&r> %msg%"
        me: "&7* %dname%&r %action%"
    relay:
        join: true
        part: true
        kick: true
        msg: true
        me: true
        color: true

advanced:
    vault_support: true
    factions_support: true
    mchat_support: true
    commands:
        command_voice: "MODE %channel% +v %nick%"
        command_devoice: "MODE %channel% -v %nick%"
        command_kick: "KICK %channel% %nick% :%reason%"
        command_ban: "MODE %channel% +b *!*@%host%\r\nKICK %channel% %nick% :%reason%"
    handlers:
        - "DefaultChatHandler"