name: MutinyIRC
version: 1.0.2
main: com.mutinycraft.irc.plugin.Plugin
author: MooseElkingtons
description: extensible IRC plugin with a simple, yet elegant design.
website: http://dev.bukkit.org/bukkit-plugins/mutinyirc/
softdepend: ['Vault', 'MChat', 'Factions']
